#!/usr/bin/env python3

import GenerateSomeQuestions as cqg
import template_question_generator as tqg
import sys
import math

article = sys.argv[1]
nquestions = int(sys.argv[2])

n1 = math.floor(nquestions / 2)
n2 = math.ceil(nquestions / 2)
assert(n1 + n2 == nquestions)

line_split_article = cqg.readFile(article)


f_ = open(article)
string_article = f_.read()
f_.close()

s = ''

s += cqg.getAllQuestions(article, n1) 

s += '\n'

s += tqg.generate_questions(string_article, n2)

s += '\n'

#s = s.split('\n')
#s = s[:nquestions]
#s = '\n'.join(s)

sys.stdout.write(s)

